# Generated by Django 4.2 on 2024-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('contactnum', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('password1', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patientname',
            new_name='pname',
        ),
    ]
