# Generated by Django 4.2 on 2024-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_rename_patientname_patient_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=100)),
                ('contactnum', models.CharField(max_length=100)),
                ('doctorname', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.CharField(max_length=150)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('address3', models.CharField(max_length=150)),
                ('pin', models.CharField(max_length=150)),
            ],
        ),
    ]
