# Generated by Django 5.0.4 on 2024-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
